export const Products = [
  {
    id: 1,
    name: "Ace pro 300",
    price: "N120,000.00",
    image: "/Ace Pro.svg",
    category: "Ratchet",
  },
  {
    id: 2,
    name: "SwiftStrike Elite",
    price: "N130,000.00",
    image: "/SwiftStrike Elite.svg",
    category: "Ratchet",
  },
  {
    id: 3,
    name: "PowerFlex 200",
    price: "N80,000.00",
    image: "/PowerFlex 200.svg",
    category: "Ratchet",
  },
  {
    id: 4,
    name: "GrandSlam Turbo",
    price: "N110,000.00",
    image: "/GrandSlam Turbo.svg",
    category: "Ratchet",
  },
  {
    id: 5,
    name: "SpinMaster 250",
    price: "N180,000.00",
    image: "/SpinMaster 250.svg",
    category: "Ratchet",
  },
  {
    id: 6,
    name: "FeatherLite 100",
    price: "N150,000.00",
    image: "/FeatherLite 100.svg",
    category: "Ratchet",
  },
  {
    id: 7,
    name: "GrandSlam Turbo",
    price: "N110,000.00",
    image: "/GrandSlam Turbo.svg",
    category: "Ratchet",
  },
  {
    id: 8,
    name: "SpinMaster 250",
    price: "N180,000.00",
    image: "/SpinMaster 250.svg",
    category: "Ratchet",
  },
  {
    id: 9,
    name: "FeatherLite 100",
    price: "N150,000.00",
    image: "/FeatherLite 100.svg",
    category: "Ratchet",
  },
  {
    id: 10,
    name: "Ace pro 300",
    price: "N120,000.00",
    image: "/Ace Pro.svg",
    category: "Ratchet",
  },
  {
    id: 11,
    name: "SwiftStrike Elite",
    price: "N130,000.00",
    image: "/SwiftStrike Elite.svg",
    category: "Ratchet",
  },
  {
    id: 12,
    name: "PowerFlex 200",
    price: "N80,000.00",
    image: "/PowerFlex 200.svg",
    category: "Ratchet",
  },
];
