export const Products = [
  {
    id: 1,
    name: "Ace pro 300",
    price: 120000.00,
    image: "/Ace Pro.svg",
    category: "Ratchet",
  },
  {
    id: 2,
    name: "SwiftStrike Elite",
    price: 130000.00,
    image: "/SwiftStrike Elite.svg",
    category: "Ratchet",
  },
  {
    id: 3,
    name: "PowerFlex 200",
    price: 80000.00,
    image: "/PowerFlex 200.svg",
    category: "Ratchet",
  },
  {
    id: 4,
    name: "GrandSlam Turbo",
    price: 110000.00,
    image: "/GrandSlam Turbo.svg",
    category: "Ratchet",
  },
  {
    id: 5,
    name: "SpinMaster 250",
    price: 180000.00,
    image: "/SpinMaster 250.svg",
    category: "Ratchet",
  },
  {
    id: 6,
    name: "FeatherLite 100",
    price: 150000.00,
    image: "/FeatherLite 100.svg",
    category: "Ratchet",
  },
  {
    id: 7,
    name: "SmashMaster 500",
    price: 110000.00,
    image: "/SmashMaster.svg",
    category: "Ratchet",
  },
  {
    id: 8,
    name: "Baseline Breaker",
    price: 200000.00,
    image: "/Baseline breaker.svg",
    category: "Ratchet",
  },
  {
    id: 9,
    name: "NetPlay Pro",
    price: 190000.00,
    image: "/NetPlay Pro.svg",
    category: "Ratchet",
  },
  {
    id: 10,
    name: "Nanoray 10F",
    price: 250000.00,
    image: "/Nanoray.svg",
    category: "Ratchet",
  },
  {
    id: 11,
    name: "Blade 950",
    price: 90000.00,
    image: "/Blade 950.svg",
    category: "Ratchet",
  },
  {
    id: 12,
    name: "Astrox 99",
    price: 45000.00,
    image: "/Astrox.svg",
    category: "Ratchet",
  },
  {
    id: 13,
    name: "Exone 98",
    price: 165000.00,
    image: "/Exone .svg",
    category: "Ratchet",
  },
  {
    id: 14,
    name: "Pure Drive",
    price: 170000.00,
    image: "/Pure drive.svg",
    category: "Ratchet",
  },
];
