export const Products = [
  {
    id: 1,
    name: "Ace pro 300",
    price: 120000.00,
    image: "/Ace Pro.svg",
    category: "Ratchet",
  },
  {
    id: 2,
    name: "SwiftStrike Elite",
    price: 130000.00,
    image: "/SwiftStrike Elite.svg",
    category: "Ratchet",
  },
  {
    id: 3,
    name: "PowerFlex 200",
    price: 80000.00,
    image: "/PowerFlex 200.svg",
    category: "Ratchet",
  },
  {
    id: 4,
    name: "GrandSlam Turbo",
    price: 110000.00,
    image: "/GrandSlam Turbo.svg",
    category: "Ratchet",
  },
  {
    id: 5,
    name: "SpinMaster 250",
    price: 180000.00,
    image: "/SpinMaster 250.svg",
    category: "Ratchet",
  },
  {
    id: 6,
    name: "FeatherLite 100",
    price: 150000.00,
    image: "/FeatherLite 100.svg",
    category: "Ratchet",
  },
  {
    id: 7,
    name: "GrandSlam Turbo",
    price: 110000.00,
    image: "/GrandSlam Turbo.svg",
    category: "Ratchet",
  },
  {
    id: 8,
    name: "SpinMaster 250",
    price: 180000.00,
    image: "/SpinMaster 250.svg",
    category: "Ratchet",
  },
  {
    id: 9,
    name: "FeatherLite 100",
    price: 150000.00,
    image: "/FeatherLite 100.svg",
    category: "Ratchet",
  },
  {
    id: 10,
    name: "Ace pro 300",
    price: 120000.00,
    image: "/Ace Pro.svg",
    category: "Ratchet",
  },
  {
    id: 11,
    name: "SwiftStrike Elite",
    price: 130000.00,
    image: "/SwiftStrike Elite.svg",
    category: "Ratchet",
  },
  {
    id: 12,
    name: "PowerFlex 200",
    price: 80000.00,
    image: "/PowerFlex 200.svg",
    category: "Ratchet",
  },
];
